[workspace]
resolver = "2"
exclude = ["examples/rust"]
members = [
    "api/test",
    "tools/update_trusted_blocks",
    "tvm_abi",
    "tvm_assembler",
    "tvm_block",
    "tvm_block_json",
    "tvm_cli",
    "tvm_client",
    "tvm_client_processing",
    "tvm_common",
    "tvm_executor",
    "tvm_sdk",
    "tvm_struct",
    "tvm_types",
    "tvm_vm",
]
[workspace.package]
version = "1.47.0"
rust-version = "1.76.0"

authors = ["TVM Labs <hello@tvmlabs.io>"]
edition = "2021"
license = "GPL-3.0"

[workspace.lints.rust]
# aim to have fmt::Debug implemented for all our public types
missing_debug_implementations = "warn"

[workspace.dependencies]
aes-ctr = "0.6.0"
anyhow = "1.0.79"
async-trait = "0.1.77"
base64 = "0.21.7"
blst = "0.3.11"
byteorder = "1.5.0"
chrono = "0.4"
clap = "4.4"
crc = "3.0.1"
curve25519-dalek = "4.1.1"
diffy = "0.3.0"
ed25519 = "2.2.3"
ed25519-dalek = "2.1.0"
external-ip = "4.2.0"
extfmt = "0.1.1"
futures = "0.3"
hex = "0.4.3"
hex-literal = "0.4.1"
lazy_static = "1.4.0"
lockfree = { git = "https://github.com/tvmlabs/lockfree" }
log = "0.4.20"
metrics = "0.22"
num = "0.4.1"
num-bigint = "0.4.4"
num-derive = "0.4.1"
num-traits = "0.2.17"
ordered-float = "4.2.0"
rand = "0.8.5"
secstr = "0.5.1"
serde = "1.0.197"
serde_derive = "1.0.197"
serde_json = "1.0.114"
serde_repr = "0.1.18"
sha2 = "0.10.8"
similar = "2.4.0"
smallvec = "1.13.1"
thiserror = "1.0.56"
tokio = "1.36.0"
x25519-dalek = "2.0.0"
zstd = "0.13.0"
#
tvm_abi = { path = "./tvm_abi" }
tvm_api = { path = "./tvm_tl/tvm_api" }
tvm_assembler = { path = "./tvm_assembler" }
tvm_block = { path = "./tvm_block" }
tvm_block_json = { path = "./tvm_block_json" }
tvm_cli = { path = "./tvm_cli" }
tvm_client = { path = "./tvm_client" }
tvm_client_processing = { path = "./tvm_client_processing" }
tvm_common = { path = "./tvm_common" }
tvm_executor = { path = "./tvm_executor" }
tvm_sdk = { path = "./tvm_sdk" }
tvm_struct = { path = "./tvm_struct" }
tvm_types = { path = "./tvm_types" }
tvm_vm = { path = "./tvm_vm" }
