[package]
description = "TON CLient Command Line Tool"
homepage = "https://tvmlabs.io"
keywords = ["TVM", "SDK", "smart contract", "tvmlabs"]
name = "tvm_cli"
readme = "README.md"
repository = "https://github.com/tvmlabs/tvm-sdk"
#
version.workspace = true
rust-version.workspace = true
#
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
api_info = { path = "../api/info" }
base64.workspace = true
dirs.workspace = true
json5.workspace = true
regex.workspace = true
serde.workspace = true
serde_derive.workspace = true
serde_json.workspace = true
tvm_client = { path = "../tvm_client" }
tvm_types.workspace = true

[dev-dependencies]
assert_cmd = "2.0.13"
predicates = "3.1.0"
