[package]
authors = ["TON Labs LTD <support@tonlabs.io>"]
description = "TON CLient Command Line Tool"
documentation = "https://docs.ton.dev"
edition = "2018"
homepage = "https://ton.dev"
keywords = ["TON", "SDK", "smart contract", "tonlabs"]
name = "tvm_cli"
readme = "README.md"
repository = "https://github.com/tvmlabs/tvm-sdk"
version = "1.46.0"

[dependencies]
api_info = { path = "../api/info" }
base64 = "0.21.7"
dirs = "5.0.1"
json5 = "0.4.1"
regex = "1.10.3"
serde = "1.0.196"
serde_derive = "1.0.196"
serde_json = "1.0.113"
tvm_client = { path = "../tvm_client" }
tvm_types = { git = "https://github.com/tvmlabs/tvm-types", tag = "3.0.1" }

[dev-dependencies]
assert_cmd = "2.0.13"
predicates = "3.1.0"
