[package]
name = "tvm_client"
version = "1.46.0"
authors = ["TON Labs LTD <support@tonlabs.io>"]
edition = "2018"
build = "build.rs"

[lib]
name = "tvm_client"
crate-type = ["cdylib", "rlib", "staticlib"]

[build-dependencies]
serde = "1.0.196"
serde_derive = "1.0.196"
serde_json = "1.0.113"

[dependencies]
api_derive = { path = "../api/derive" }
api_info = { path = "../api/info" }
tvm_client_processing = { default-features = false, path = "../tvm_client_processing" }
tvm_sdk = { default-features = false, path = "../tvm_sdk" }

tvm_abi = { git = "https://github.com/tvmlabs/tvm-abi", tag = "3.0.0" }
tvm_block = { git = "https://github.com/tvmlabs/tvm-block", tag = "2.0.0" }
tvm_block_json = { git = "https://github.com/tvmlabs/tvm-block-json", tag = "0.8.0" }
tvm_executor = { features = ["signature_with_id"], git = "https://github.com/tvmlabs/tvm-executor", tag = "2.0.0" }
tvm_struct = { git = "https://github.com/tvmlabs/tvm-struct", tag = "2.0.0" }
tvm_types = { git = "https://github.com/tvmlabs/tvm-types", tag = "3.0.1" }
tvm_vm = { features = ["signature_with_id", "signature_no_check"], git = "https://github.com/tvmlabs/tvm-vm", tag = "2.0.0" }

lockfree = { git = "https://github.com/tvmlabs/lockfree", package = "lockfree" }
sodalite = { features = ["rand"], git = "https://github.com/tvmlabs/sodalite" }


aes = "0.7.4"
anyhow = "1.0.79"
async-trait = "0.1.77"
base58 = "0.2.0"
base64 = "0.21.7"
bincode = "1.3.3"
block-modes = "0.8.1"
byteorder = "1.5.0"
chacha20 = "0.6.0"
chrono = "0.4.33"
crc = "3.0.1"
ed25519-dalek = "2.1.0"
futures = "0.3.30"
hex = "0.4.3"
hmac = "0.11.0"
lazy_static = "1.4.0"
libsecp256k1 = "0.6.0"
log = "0.4.20"
lru = "0.12.2"
num-bigint = "0.4.4"
num-derive = "0.4.1"
num-traits = "0.2.17"
pbkdf2 = { default-features = false, version = "0.8.0" }
rand = "0.8.5"
regex = "1.10.3"
scrypt = { default-features = false, version = "0.7.0" }
serde = "1.0.196"
serde_derive = "1.0.196"
serde_json = "1.0.113"
serde_repr = "0.1.18"
sha2 = "0.9.5"
thiserror = "1.0.56"
tiny-bip39 = "1.0.0"
tokio = { default-features = false, features = ["sync"], version = "1.35.1" }
tokio-stream = { default-features = false, version = "0.1.14" }
zeroize = { features = ["zeroize_derive"], version = "1.7.0" }

# optional
zstd = { default-features = false, optional = true, version = "0.13.0" }

# optional for std
reqwest = { features = ["cookies"], optional = true, version = "0.11.11", default-features = false }
tokio-tungstenite = { optional = true, version = "0.17.1" }

# optional for wasm
indexed_db_futures = { default-features = false, optional = true, version = "0.4.1" }
js-sys = { optional = true, version = "0.3.67" }
wasm-bindgen = { optional = true, version = "0.2.90" }
wasm-bindgen-futures = { optional = true, version = "0.4.40" }

[dependencies.home]
optional = true
version = "0.5.9"

[dependencies.web-sys]
features = [
    "ErrorEvent",
    "FileReader",
    "Headers",
    "MessageEvent",
    "ProgressEvent",
    "Request",
    "RequestInit",
    "Response",
    "Window",
    "WebSocket",
]
optional = true
version = "0.3.67"

[dev-dependencies]
dirs = "5.0.1"
graphql-parser = "0.4.0"
log4rs = "1.2.0"
pretty_assertions = "1.4.0"


[features]
default = ["std", "native-tls"]
include-zstd = ["tvm_block/gosh", "tvm_vm/gosh"]
std = [
    "tokio/rt-multi-thread",
    "tokio/macros",
    "tokio/time",
    "tokio/net",
    "tokio/fs",
    "home",
    "include-zstd",
    "zstd",
]
native-tls = ["reqwest/default", "tokio-tungstenite/native-tls"]
native-tls-vendored = [
    "reqwest/native-tls-vendored",
    "tokio-tungstenite/native-tls-vendored",
]
rustls-tls-native-roots = [
    "reqwest/rustls-tls-native-roots",
    "tokio-tungstenite/rustls-tls-native-roots",
]
rustls-tls-webpki-roots = [
    "reqwest/rustls-tls-webpki-roots",
    "tokio-tungstenite/rustls-tls-webpki-roots",
]
wasm = ["wasm-base", "include-zstd", "zstd", "zstd/thin", "zstd/wasm"]
wasm-base = [
    "chrono/wasmbind",
    "indexed_db_futures",
    "js-sys",
    "wasm-bindgen",
    "wasm-bindgen-futures",
    "web-sys",
]
