[package]
authors = ["TON Labs LTD <support@tonlabs.io>"]
edition = "2018"
name = "api_info"
version = "1.46.0"

[dependencies]
serde = "1.0.196"
serde_derive = "1.0.196"
serde_json = "1.0.113"

[lib]
name = "api_info"
