[package]
edition = "2018"
name = "update_trusted_blocks"
version = "0.1.0"

[dependencies]
bincode = "1.3.3"
serde = "1.0.130"
serde_derive = "1.0.130"
serde_json = "1.0.68"
tokio = { default-features = false, features = ["sync", "fs"], version = "1" }
tvm_client = { path = "../../tvm_client" }
tvm_types = { git = "https://github.com/tvmlabs/tvm-types", tag = "3.0.1" }
